stages:
  - build
  - lint
  - test

default:
  tags:
    - linux

rust-build:
  stage: build
  image: rust:latest
  needs: []
  script:
    - cargo build

go-build:
  stage: build
  image: golang:latest
  needs: []
  script:
    - cd gin
    - go build

format:
  stage: lint
  image: rust:latest
  needs: []
  script:
    - cargo fmt --check

clippy:
  stage: lint
  image: rust:latest
  needs: []
  script:
    - cargo clippy -- -Dwarnings

test:
  stage: test
  image: rust:latest
  needs: []
  script:
    - cargo test
